[project]
name = "kooplexquery"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12.1"
dependencies = [
    "aiosqlite>=0.21.0",
    "chromadb>=1.1.1",
    "gpt4all>=2.8.2",
    "ipykernel>=7.1.0",
    "kaleido==0.2.1",
    "langchain>=1.0.0",
    "langchain-chroma",
    "langchain-community",
    "langchain-core",
    "langchain-experimental",
    "langchain-mcp-adapters>=0.1.13",
    "langchain-ollama",
    "langchain-openai",
    "langchain-text-splitters>=1.0.0",
    "langgraph-checkpoint-sqlite>=3.0.1",
    "nbformat>=5.10.4",
    "pandas>=2.3.3",
    "psycopg2>=2.9.11",
    "pymssql>=2.3.13",
    "python-dotenv>=1.1.1",
    "sqlalchemy>=2.0.44",
    "streamlit-elements>=0.1.0",
    "streamlit-extras>=0.7.8",
    "streamlit-keyup>=0.3.0",
]


[tool]
description = "A command-line application for querying and managing data."
authors = ["Your Name <your.email@example.com>"]
license = "MIT"


[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"


[tool.poetry.scripts]
kooplexquery = "kooplexquery.prompt"
#sqlvalidator = "sqlValidator.sql_validator_app"

[tool.setuptools.packages.find]
include = ["kooplexQuery*", "utils*"]
exclude = ["src_archived*", "sqlValidator*"]

[project.scripts]
kooplexquery = "kooplexQuery.prompt:main"
#sqlvalidator = "sqlValidator.sql_validator_app:main"
